sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
  - "pypy"

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq nodejs
- npm install yarn

install: install_script.sh

# command to run tests
script:
    - cd front && yarn test
    #- cd back && nosetests tests
